[tool.poetry]
name = "lib-ml"
version = "0.1.0"
description = "Contains the pre-processing logic for data that is used for training or queries."
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
